### ISSUE TITLE
SyntaxError while running "juju scaleway bootstrap"

### ISSUE THREAD

**Issue by gerardmrk** [scaleway/juju-scaleway#4]
I was following the instructions for setting up. Downloaded juju via homebrew, and juju-scaleway via pip3.
This was the error i got:

Traceback (most recent call last):
  File "/usr/local/bin/juju-scaleway", line 9, in <module>
    load_entry_point('juju-scaleway==1.0.0', 'console_scripts', 'juju-scaleway')()
  File "/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 2345, in load
  File "/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/usr/local/lib/python3.4/site-packages/juju_scaleway/cli.py", line 107
    except ConfigError, e:
                      ^
SyntaxError: invalid syntax
ERROR subprocess encountered error code 1

**Comment by brmzkw** [comment]
Yeyyy.. we didn't test the plugin with Python3. I made a fix (https://github.com/scaleway/juju-scaleway/commit/b4938c9307c3ca90013cf136c9f024807dd2aff5) and release the version 1.0.1. Everything should work now :)

**Comment by gerardmrk** [comment]
Thanks! Although, I actually got it to work by uninstalling pip3 and just used OS X's default python to download pip and used that version instead, and it worked!

**Comment by brmzkw** [comment]
Yep, the version packaged with OSX is Python2 :)
